apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../../base/my-website

images:
- name: my-website
  newName: public.ecr.aws/r8m4q7l9/my-website
  newTag: ae11e0904e39e59eb0090c4843ed0f1fabcb5ce2
  
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.bug-website.com
  target:
    kind: Ingress
    name: my-website
