apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bugbug-website-prod
  namespace: argocd
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  project: sample-project
  source:
    repoURL: https://github.com/bug8499/IaC-GitOps-Vultr
    targetRevision: main
    path: GitOps/apps/overlays/prod/bugbug-website
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true