apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../../base/bugbug-website

images:
- name: bugbug-website
  newName: ghcr.io/bug8499/bugbug-website
  newTag: 37d4a6c0543fe162b87588d94dd6cbbd9316168a

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: main-bugbug.bug-website.com
  target:
    kind: Ingress
    name: bugbug-website
