apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../../base/bugbug-website

images:
- name: bugbug-website
  newName: ghcr.io/bug8499/bugbug-website
  newTag: 20a03638342a78ff5182ab2e10d30ce310e4cbc6

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: main-bugbug.bug-website.com
  target:
    kind: Ingress
    name: bugbug-website
