apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../../base/bugbug-website

images:
- name: bugbug-website
  newName: ghcr.io/bug8499/bugbug-website
  newTag: 81862a9568f6728505787f99afb39d5a1a3e87da
  
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev-bugbug.bug-website.com
  target:
    kind: Ingress
    name: bugbug-website
