apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../../base/bugbug-website

images:
- name: bugbug-website
  newName: ghcr.io/bug8499/bugbug-website
  newTag: c88ab76ee2806015fd4690d7d71ff6aeef108883
  
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev-bugbug.bug-website.com
  target:
    kind: Ingress
    name: bugbug-website
