apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meme-website-dev
  namespace: argocd
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  project: sample-project
  source:
    repoURL: https://github.com/bug8499/IaC-GitOps
    targetRevision: main
    path: GitOps/apps/overlays/dev/meme-website   # ← ชี้ที่ overlay ของ website
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true